# NB and Logistic Regression Project 

Welcome to NB and Logistic Regression Project! Go ahead and follow the directions below.

Tasks:

EDA and Basic Data Preprocessing and Preparation [Marks:2]

Train Model using different variations of NB [Marks:2+1]

Compare time and accuracy of different NB algorithms [Marks:0.5]

Train Model with Logistic Regression with different solver and penalty [Marks:2+1]

Compare time and accuracy of different Logistic Regression algorithms [Marks:0.5]

Plot confusion Matrix for the final model selected [Marks:1]



Above tasks are mentioned in the notebook, The notebook has empty
code cells. Fill the empty code cells with appropriate python code.
Convert the notebook to HTML format and upload on Canvas. Submit ONLY
HTML format of the notebook.

**Build a classification model which will recognise the activities through the mobile sensor like walking, walking_upstairs  ,walking_downstairs ,sitting  ,standing,lying.The topic Human Activity recognition is in research and has its own advantages like anomaly detection, for healthy diet maintenance fitness bands are used , measuring stress level ,for monitoring employees ,for heartbeat pulse rate etc. In this project we are going to focus on  the dataset which was carried out through experiments with a group of 30 volunteers wearing a smartphone.The experiments have been video-recorded to label the data manually.The  main motto is to use the dataset and work with the libraries like scikit learn and machine learning related libraries and algorithms while training.**

# <font color='red'>Download and submit only HTML file</font>

# Import Libraries
**Import pandas,seaborn, and the usual libraries.**

In [99]:
import pandas as pd
import seaborn as sns

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import sklearn
import statsmodels as sm

# EDA and Basic Data Preprocessing and Preparation [Marks:2]
**If trying auto EDA do it in a different notebook and only highlight important, interesting or unusual pattern that you noticed in the data**

<font color='red'>Give justification for your choices and techniques used for every step</font>

In [58]:
df = pd.read_csv('NISHITH - human_activity.csv')
df.head()           #First five rows

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  tBodyAcc-std()-X  \
0           0.288585          -0.020294          -0.132905         -0.995279   
1           0.278419          -0.016411          -0.123520         -0.998245   
2           0.279653          -0.019467          -0.113462         -0.995380   
3           0.279174          -0.026201          -0.123283         -0.996091   
4           0.276629          -0.016570          -0.115362         -0.998139   

   tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  tBodyAcc-mad()-Y  \
0         -0.983111         -0.913526         -0.995112         -0.983185   
1         -0.975300         -0.960322         -0.998807         -0.974914   
2         -0.967187         -0.978944         -0.996520         -0.963668   
3         -0.983403         -0.990675         -0.997099         -0.982750   
4         -0.980817         -0.990482         -0.998321         -0.979672   

   tBodyAcc-mad()-Z  tBodyAcc-max()-X  ...  fBodyBodyGyroJerkMag-kurtosis()  \
0         -0.923527         -0.934724  ...                        -0.710304   
1         -0.957686         -0.943068  ...                        -0.861499   
2         -0.977469         -0.938692  ...                        -0.760104   
3         -0.989302         -0.938692  ...                        -0.482845   
4         -0.990441         -0.942469  ...                        -0.699205   

   angle(tBodyAccMean,gravity)  angle(tBodyAccJerkMean),gravityMean)  \
0                    -0.112754                              0.030400   
1                     0.053477                             -0.007435   
2                    -0.118559                              0.177899   
3                    -0.036788                             -0.012892   
4                     0.123320                              0.122542   

   angle(tBodyGyroMean,gravityMean)  angle(tBodyGyroJerkMean,gravityMean)  \
0                         -0.464761                             -0.018446   
1                         -0.732626                              0.703511   
2                          0.100699                              0.808529   
3                          0.640011                             -0.485366   
4                          0.693578                             -0.615971   

   angle(X,gravityMean)  angle(Y,gravityMean)  angle(Z,gravityMean)  subject  \
0             -0.841247              0.179941             -0.058627        1   
1             -0.844788              0.180289             -0.054317        1   
2             -0.848933              0.180637             -0.049118        1   
3             -0.848649              0.181935             -0.047663        1   
4             -0.847865              0.185151             -0.043892        1   

   Activity  
0  STANDING  
1  STANDING  
2  STANDING  
3  STANDING  
4  STANDING  

[5 rows x 563 columns]

In [ ]:
                            #Data Analysis
print("*********************************************")
df.info()         #Gives info on each and every column and their data types stored
print("*********************************************")

In [9]:
df.shape          #number of rows and columns

(7352, 563)

In [10]:
df.describe()     #Gives count, mean, stdev, min value, max value, common percentiles

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  \
count        7352.000000        7352.000000        7352.000000   
mean            0.274488          -0.017695          -0.109141   
std             0.070261           0.040811           0.056635   
min            -1.000000          -1.000000          -1.000000   
25%             0.262975          -0.024863          -0.120993   
50%             0.277193          -0.017219          -0.108676   
75%             0.288461          -0.010783          -0.097794   
max             1.000000           1.000000           1.000000   

       tBodyAcc-std()-X  tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  \
count       7352.000000       7352.000000       7352.000000       7352.000000   
mean          -0.605438         -0.510938         -0.604754         -0.630512   
std            0.448734          0.502645          0.418687          0.424073   
min           -1.000000         -0.999873         -1.000000         -1.000000   
25%           -0.992754         -0.978129         -0.980233         -0.993591   
50%           -0.946196         -0.851897         -0.859365         -0.950709   
75%           -0.242813         -0.034231         -0.262415         -0.292680   
max            1.000000          0.916238          1.000000          1.000000   

       tBodyAcc-mad()-Y  tBodyAcc-mad()-Z  tBodyAcc-max()-X  ...  \
count       7352.000000       7352.000000       7352.000000  ...   
mean          -0.526907         -0.606150         -0.468604  ...   
std            0.485942          0.414122          0.544547  ...   
min           -1.000000         -1.000000         -1.000000  ...   
25%           -0.978162         -0.980251         -0.936219  ...   
50%           -0.857328         -0.857143         -0.881637  ...   
75%           -0.066701         -0.265671         -0.017129  ...   
max            0.967664          1.000000          1.000000  ...   

       fBodyBodyGyroJerkMag-skewness()  fBodyBodyGyroJerkMag-kurtosis()  \
count                      7352.000000                      7352.000000   
mean                         -0.307009                        -0.625294   
std                           0.321011                         0.307584   
min                          -0.995357                        -0.999765   
25%                          -0.542602                        -0.845573   
50%                          -0.343685                        -0.711692   
75%                          -0.126979                        -0.503878   
max                           0.989538                         0.956845   

       angle(tBodyAccMean,gravity)  angle(tBodyAccJerkMean),gravityMean)  \
count                  7352.000000                           7352.000000   
mean                      0.008684                              0.002186   
std                       0.336787                              0.448306   
min                      -0.976580                             -1.000000   
25%                      -0.121527                             -0.289549   
50%                       0.009509                              0.008943   
75%                       0.150865                              0.292861   
max                       1.000000                              1.000000   

       angle(tBodyGyroMean,gravityMean)  angle(tBodyGyroJerkMean,gravityMean)  \
count                       7352.000000                           7352.000000   
mean                           0.008726                             -0.005981   
std                            0.608303                              0.477975   
min                           -1.000000                             -1.000000   
25%                           -0.482273                             -0.376341   
50%                            0.008735                             -0.000368   
75%                            0.506187                              0.359368   
max                            0.998702                     

In [ ]:
df.describe().shape

In [ ]:
#Dataprep Part

from dataprep.eda import plot
from dataprep.eda import create_report
# plot(df)
report = create_report(df)

In [7]:
report.save('report_01.html')

Report has been saved to report_01.html!


## Null/Outlier Treatment

In [7]:
df.isnull().sum()

tBodyAcc-mean()-X       0
tBodyAcc-mean()-Y       0
tBodyAcc-mean()-Z       0
tBodyAcc-std()-X        0
tBodyAcc-std()-Y        0
                       ..
angle(X,gravityMean)    0
angle(Y,gravityMean)    0
angle(Z,gravityMean)    0
subject                 0
Activity                0
Length: 563, dtype: int64

We see that there are no Null values, we proceed with Finding outliers

In [ ]:
def boxPlot(df,feature):
        df.boxplot(column = [feature])
        plt.grid(False)
        plt.show()

# outliers = []
# # @brief returns a list of indices of all outliers
# # @param dataframe and the feature
# def detect_outliers_iqr(df):
#     df = sorted(df)
#     q1 = np.percentile(df, 25)
#     q3 = np.percentile(df, 75)
#     # print(q1, q3)
#     IQR = q3-q1
#     lwr_bound = q1-(1.5*IQR)
#     upr_bound = q3+(1.5*IQR)
#     # print(lwr_bound, upr_bound)
#     for i in df: 
#         if (i<lwr_bound or i>upr_bound):
#             outliers.append(i)
#     return outliers

# @brief returns a list of indices of all outliers
# @param dataframe and the feature
def outliers(df,feature):
    Q1 = df[feature].quantile(0.25)
    Q3 = df[feature].quantile(0.75)
    IQR = Q3 - Q1 
    lowerBound = Q1 - 1.5 * IQR
    upperBound = Q3 + 1.5 * IQR

    lst = df.index[ (df[feature] < lowerBound ) | (df[feature] > upperBound) ]
    return lst 


In [ ]:
#Checking if the function works
boxPlot(df,"tBodyAcc-mean()-X")

In [ ]:
#extracting all needed columns to pass into the outlier functions
columns = []
for i in df.columns:
    columns.append(i)
# print(columns)
#removing last two elements form columns
columns.pop()
x_columns = columns #storing this for x_data below
columns.pop()
print(columns)

In [48]:
index_list = []
# @brief Creating an index list for all columns
for feature in columns:
    index_list.extend(outliers(df,feature))


In [ ]:
print(index_list)

In [66]:
def remove(df,ls):
    ls = sorted(set(ls))
    df = df.drop(ls)
    return df
df_new = remove(df,index_list)
df_new.shape

(6883, 563)

## Remove non-Important Features

No features are removed since all features in the dataset are combinations of human movements in x,y,z directions, so nothing can be irrelevant in training our model

## Split Predictor and Target Varaibles

In [78]:
x_data = df_new[x_columns]
# x_data.head()
y_data = df_new["Activity"]     #y is target variable
# print(y_data)


## Split Training and Testing Data Set

In [80]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x_data,
    y_data ,
    test_size = 0.2,
    shuffle = False )
# print(x_train)


## Standardize the Variables

In [87]:
from sklearn.preprocessing import StandardScaler
x_train_scaled = StandardScaler().fit_transform(x_train)
x_train_scaled.shape

(5506, 561)

In [86]:
x_test_scaled = StandardScaler().fit_transform(x_test)
x_test_scaled.shape

(1377, 561)

# Train Model using different variations of NB [Marks:2+1]
**Breifly describe & Justify why one of the variant performed better compared to others**

In [117]:
#Bernouli
from sklearn.naive_bayes import BernoulliNB

model_b = BernoulliNB()
model_b.fit(x_train,y_train)

BernoulliNB()

In [128]:
#Bernouli
from sklearn.metrics import accuracy_score

pred_train = model_b.predict(x_train)

print("Accuracy score on train : ",accuracy_score(y_train,pred_train))

pred_test_b = model_b.predict(x_test)
print("Accuracy score on test : ",accuracy_score(y_test,pred_test_b))

Accuracy score on train :  0.8694151834362513
Accuracy score on test :  0.8569353667392883


In [119]:
#Gaussian
from sklearn.naive_bayes import GaussianNB

model_g = GaussianNB()
model_g.fit(x_train,y_train)

GaussianNB()

In [129]:
#Gaussian
from sklearn.metrics import accuracy_score

pred_train = model_g.predict(x_train)

print("Accuracy score on train : ",accuracy_score(y_train,pred_train))

pred_test_g = model_g.predict(x_test)
print("Accuracy score on test : ",accuracy_score(y_test,pred_test_g))

Accuracy score on train :  0.7050490374137305
Accuracy score on test :  0.7116920842411039


We see that bernoulli's performed better than Gaussian in this case. When we standardised the data, it got closer in resemblance to bernouli's distribution which can be one of the reasons for this. Also, Gaussian might be less accurate than Gaussian because in Gaussian there are two hyperparameters which need to be estimated on maximum likelihood basis

# Compare time and accuracy of different NB algos [Marks:0.5]

In [132]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(x_train)
x_train_minmax = scaler.fit_transform(x_train)
x_test_minmax = scaler.fit_transform(x_test)


In [127]:
from sklearn.naive_bayes import MultinomialNB
model_m = MultinomialNB()
model_m.fit(x_train_minmax,y_train)

from sklearn.naive_bayes import ComplementNB
model_c = ComplementNB()
model_c.fit(x_train_minmax, y_train)

from sklearn.naive_bayes import CategoricalNB
model_categ = CategoricalNB(min_categories= 100)
model_categ.fit(x_train_minmax,y_train)


CategoricalNB(min_categories=100)

In [133]:
from sklearn.metrics import accuracy_score
pred_test_multi = model_m.predict(x_test_minmax)
pred_test_complem = model_c.predict(x_test_minmax)
pred_test_categ = model_categ.predict(x_test_minmax)

In [134]:
print("Accuracy score on test with Bernoulli: ",accuracy_score(y_test,pred_test_b))
print("Accuracy score on test with Gaussian: ",accuracy_score(y_test,pred_test_g))
print("Accuracy score on test with Multinomial: ",accuracy_score(y_test,pred_test_multi))
print("Accuracy score on test with Complement: ",accuracy_score(y_test,pred_test_complem))
print("Accuracy score on test with Categorial: ",accuracy_score(y_test,pred_test_categ))


Accuracy score on test with Bernoulli:  0.8569353667392883
Accuracy score on test with Gaussian:  0.7116920842411039
Accuracy score on test with Multinomial:  0.7283950617283951
Accuracy score on test with Complement:  0.36673928830791575
Accuracy score on test with Categorial:  0.21423384168482207


# Train Model with Logistic Regression with different solver and penalty [Marks:2+1]
**Justify why one of the solver or penalty performed better compared to others**

In [88]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(penalty='l1',solver='liblinear',max_iter = 100000)
model.fit(x_train_scaled,y_train)
print('Training accuracy score: {0:0.4f}'. format(model.score(x_train_scaled,y_train)))
print('Test accuracy score: {0:0.4f}'. format(model.score(x_test_scaled,y_test)))

Training accuracy score: 0.9962
Test accuracy score: 0.9695


In [90]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(penalty='l2',solver='lbfgs',max_iter = 100000)
model.fit(x_train_scaled,y_train)
print('Training accuracy score: {0:0.4f}'. format(model.score(x_train_scaled,y_train)))
print('Test accuracy score: {0:0.4f}'. format(model.score(x_test_scaled,y_test)))

Training accuracy score: 0.9980
Test accuracy score: 0.9572


Liblinear with l1 performed better on test data set since we do not have the multinomial loss for which lbfgs was designed to handle. An interesting observation here is that lbfgs took quite sometime to train the model

# Compare time and accuracy of different Logistic Regression algos [Marks:0.5]

In [96]:
model_1 = LogisticRegression(penalty='l1',solver='liblinear',max_iter = 100000)
model_4 = LogisticRegression(penalty='l2',solver='liblinear',max_iter = 100000)
model_5 = LogisticRegression(penalty='l2',solver='lbfgs',max_iter = 100000)
model_6 = LogisticRegression(penalty='l2',solver='newton-cg',max_iter = 100000)


In [98]:
model_1.fit(x_train_scaled,y_train)
print('accuracy score in l1+liblinear = {0:0.4f}'. format(model_1.score(x_test_scaled,y_test)))


model_4.fit(x_train_scaled,y_train)
print('accuracy score in l2+liblinear = {0:0.4f}'. format(model_4.score(x_test_scaled,y_test)))

model_5.fit(x_train_scaled,y_train)
print('accuracy score in l2+lbgfs = {0:0.4f}'. format(model_5.score(x_test_scaled,y_test)))

model_6.fit(x_train_scaled,y_train)
print('accuracy score in l2+newton-cg = {0:0.4f}'. format(model_6.score(x_test_scaled,y_test)))


accuracy score in l1+liblinear = 0.9710
accuracy score in l2+liblinear = 0.9637
accuracy score in l2+lbgfs = 0.9572
accuracy score in l2+newton-cg = 0.9564


# Plot confusion Matrix for the final model selected [Marks:1]

In [105]:
from sklearn.metrics import confusion_matrix
y_predicted = model_1.predict(x_test)
cm = confusion_matrix(y_test, y_predicted)

/home/nishith/.local/lib/python3.8/site-packages/sklearn/base.py:443: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(


In [107]:
print(cm) 

[[106 168  19   0   0   0]
 [  0 215   2   0   0   0]
 [  0 107 115   0   0   0]
 [  0  23   0 206   0   0]
 [  0 146  19   1  33   1]
 [  0  80  41   0   0  95]]
